import { Hono } from "hono";
import type { Context } from "hono";
import s3Routes from "./s3";
import s3ConfigRoutes from "./s3-config";
import s3ObjectRoutes from "./s3-objects";
import dynamodbRoutes from "./dynamodb";
import dynamodbAdvancedRoutes from "./dynamodb-advanced";
import rdsRoutes from "./rds";
import ec2Routes from "./ec2";
import sqsRoutes from "./sqs";
import snsRoutes from "./sns";
import eventsRoutes from "./events";
import logsRoutes from "./logs";
import lambdaRoutes from "./lambda";
import cloudwatchRoutes from "./cloudwatch";
import iamRoutes from "./iam";
import secretsmanagerRoutes from "./secretsmanager";
import cloudformationRoutes from "./cloudformation";
import kmsRoutes from "./kms";
import ecsRoutes from "./ecs";
import ssmRoutes from "./ssm";
import route53Routes from "./route53";
import apiGatewayRoutes from "./apigateway";
import stsRoutes from "./sts";
import appsyncRoutes from "./appsync";
import schedulerRoutes from "./scheduler";
import ecrRoutes from "./ecr";
import elbRoutes from "./elb";
import sesRoutes from "./ses";
import eksRoutes from "./eks";
import autoscalingRoutes from "./autoscaling";
import cloudfrontRoutes from "./cloudfront";
import kinesisRoutes from "./kinesis";
import neptuneRoutes from "./neptune";
import pipesRoutes from "./pipes";
import cognitoRoutes from "./cognito";
import apigatewayv2Routes from "./apigatewayv2";
import acmRoutes from "./acm";
import cloudtrailRoutes from "./cloudtrail";
import configserviceRoutes from "./configservice";
import appconfigRoutes from "./appconfig";
import cloudmapRoutes from "./cloudmap";
import athenaRoutes from "./athena";
import glueRoutes from "./glue";
import firehoseRoutes from "./firehose";

const router = new Hono();

router.route("/s3", s3Routes);
router.route("/s3", s3ConfigRoutes);
router.route("/s3", s3ObjectRoutes);
router.route("/dynamodb", dynamodbRoutes);
router.route("/dynamodb", dynamodbAdvancedRoutes);
router.route("/rds", rdsRoutes);
router.route("/ec2", ec2Routes);
router.route("/sqs", sqsRoutes);
router.route("/sns", snsRoutes);
router.route("/events", eventsRoutes);
router.route("/logs", logsRoutes);
router.route("/lambda", lambdaRoutes);
router.route("/cloudwatch", cloudwatchRoutes);
router.route("/iam", iamRoutes);
router.route("/secretsmanager", secretsmanagerRoutes);
router.route("/cloudformation", cloudformationRoutes);
router.route("/kms", kmsRoutes);
router.route("/ecs", ecsRoutes);
router.route("/ssm", ssmRoutes);
router.route("/route53", route53Routes);
router.route("/apigateway", apiGatewayRoutes);
router.route("/sts", stsRoutes);
router.route("/appsync", appsyncRoutes);
router.route("/scheduler", schedulerRoutes);
router.route("/ecr", ecrRoutes);
router.route("/elb", elbRoutes);
router.route("/ses", sesRoutes);
router.route("/eks", eksRoutes);
router.route("/autoscaling", autoscalingRoutes);
router.route("/cloudfront", cloudfrontRoutes);
router.route("/kinesis", kinesisRoutes);
router.route("/neptune", neptuneRoutes);
router.route("/pipes", pipesRoutes);
router.route("/cognito", cognitoRoutes);
router.route("/apigatewayv2", apigatewayv2Routes);
router.route("/acm", acmRoutes);
router.route("/cloudtrail", cloudtrailRoutes);
router.route("/configservice", configserviceRoutes);
router.route("/appconfig", appconfigRoutes);
router.route("/cloudmap", cloudmapRoutes);
router.route("/athena", athenaRoutes);
router.route("/glue", glueRoutes);
router.route("/firehose", firehoseRoutes);

router.get("/", (c: Context) => {
  return c.json({ message: "AWS routes available. Services registered: s3, dynamodb, rds, ec2, sqs, sns, events, logs, lambda, cloudwatch, iam, secretsmanager, cloudformation, kms, ecs, ssm, route53, apigateway, sts, appsync, scheduler, ecr, elb, ses, eks, autoscaling, cloudfront, kinesis, neptune, pipes, cognito, apigatewayv2, acm, cloudtrail, configservice, appconfig, cloudmap" });
});

export default router;
