export const SERVICE_CATEGORIES: Record<string, string[]> = {
  "Compute":        ["ec2", "lambda", "ecs", "eks", "autoscaling", "codebuild"],
  "Storage":        ["s3", "ecr"],
  "Database":       ["dynamodb", "rds", "neptune", "elasticache"],
  "Networking":     ["elasticloadbalancing", "route53", "cloudfront", "apigateway", "apigatewayv2", "appsync"],
  "Messaging":      ["sqs", "sns", "events", "kinesis", "pipes", "scheduler", "email"],
  "Security":       ["iam", "sts", "cognito-idp", "kms", "secretsmanager", "acm", "wafv2"],
  "Management":     ["cloudformation", "monitoring", "logs", "ssm", "config", "appconfig", "appconfigdata", "cloudtrail", "servicediscovery"],
  "Analytics":      ["athena", "glue", "firehose", "states", "kafka", "es"],
  "ML/AI":          ["bedrock-runtime", "textract", "transcribe"],
  "Billing":        ["ce", "cur", "bcm-data-exports", "pricing", "tagging"],
  "Developer Tools":["codedeploy", "codebuild"],
  "Migration":      ["backup", "transfer"],
};

export const SERVICE_LABELS: Record<string, string> = {
  "s3": "S3",
  "sqs": "SQS",
  "sns": "SNS",
  "lambda": "Lambda",
  "dynamodb": "DynamoDB",
  "iam": "IAM",
  "sts": "STS",
  "kms": "KMS",
  "secretsmanager": "Secrets Manager",
  "cloudformation": "CloudFormation",
  "events": "EventBridge",
  "ssm": "Systems Manager",
  "kinesis": "Kinesis",
  "logs": "CloudWatch Logs",
  "monitoring": "CloudWatch Metrics",
  "ec2": "EC2",
  "ecs": "ECS",
  "ecr": "ECR",
  "rds": "RDS",
  "elasticache": "ElastiCache",
  "cognito-idp": "Cognito",
  "acm": "ACM",
  "route53": "Route 53",
  "cloudfront": "CloudFront",
  "apigateway": "API Gateway",
  "apigatewayv2": "API Gateway V2",
  "athena": "Athena",
  "glue": "Glue",
  "firehose": "Kinesis Firehose",
  "states": "Step Functions",
  "kafka": "MSK",
  "es": "OpenSearch",
  "servicediscovery": "Cloud Map",
  "scheduler": "EventBridge Scheduler",
  "pipes": "EventBridge Pipes",
  "email": "SES",
  "elasticloadbalancing": "ELB",
  "neptune": "Neptune",
  "codebuild": "CodeBuild",
  "codedeploy": "CodeDeploy",
  "eks": "EKS",
  "backup": "Backup",
  "transfer": "Transfer Family",
  "cloudtrail": "CloudTrail",
  "appconfig": "AppConfig",
  "appconfigdata": "AppConfig Data",
  "bedrock-runtime": "Bedrock Runtime",
  "textract": "Textract",
  "transcribe": "Transcribe",
  "pricing": "Pricing",
  "ce": "Cost Explorer",
  "cur": "Cost & Usage Report",
  "bcm-data-exports": "BCM Data Exports",
  "tagging": "Resource Groups Tagging",
  "config": "Config",
  "autoscaling": "Auto Scaling",
  "appsync": "AppSync",
  "wafv2": "WAF v2",
  "ec2messages": "EC2 Messages",
};

export function getServiceLabel(externalKey: string): string {
  return SERVICE_LABELS[externalKey] ?? externalKey;
}
