export const SERVICE_CATEGORIES: Record<string, string[]> = {
  "Compute":        ["ec2", "lambda", "autoscaling"],
  "Containers":     ["ecs", "ecr", "eks"],
  "Storage":        ["s3"],
  "Database":       ["dynamodb", "rds", "neptune", "elasticache", "docdb", "memorydb"],
  "Networking & Content Delivery": ["elasticloadbalancing", "route53", "cloudfront", "apigateway", "apigatewayv2", "appsync"],
  "Application Integration": ["sqs", "sns", "events", "kinesis", "pipes", "scheduler", "email", "states", "appsync"],
  "Security, Identity & Compliance": ["iam", "sts", "cognito-idp", "kms", "secretsmanager", "acm", "wafv2"],
  "Management & Governance": ["cloudformation", "monitoring", "logs", "ssm", "config", "appconfig", "appconfigdata", "cloudtrail", "servicediscovery"],
  "Analytics":      ["athena", "glue", "firehose", "kafka", "es", "emr"],
  "Machine Learning": ["bedrock-runtime", "textract", "transcribe"],
  "Cost Management": ["ce", "cur", "bcm-data-exports", "pricing", "tagging"],
  "Developer Tools":["codedeploy", "codebuild"],
  "Migration & Transfer": ["backup", "transfer"],
};

export const CATEGORY_ORDER = [
  "Application Integration",
  "Compute",
  "Containers",
  "Database",
  "Developer Tools",
  "Storage",
  "Networking & Content Delivery",
  "Security, Identity & Compliance",
  "Management & Governance",
  "Analytics",
  "Machine Learning",
  "Cost Management",
  "Migration & Transfer",
] as const;

export const SERVICE_CATEGORY_MAP: Record<string, string> = {
  ec2: "Compute", lambda: "Compute", autoscaling: "Compute",
  ecs: "Containers", ecr: "Containers", eks: "Containers",
  s3: "Storage", s3vectors: "Storage",
  dynamodb: "Database", rds: "Database", neptune: "Database", elasticache: "Database", docdb: "Database", memorydb: "Database",
  elasticloadbalancing: "Networking & Content Delivery", route53: "Networking & Content Delivery", cloudfront: "Networking & Content Delivery",
  apigateway: "Networking & Content Delivery", apigatewayv2: "Networking & Content Delivery", appsync: "Application Integration",
  sqs: "Application Integration", sns: "Application Integration", events: "Application Integration", kinesis: "Application Integration",
  pipes: "Application Integration", scheduler: "Application Integration", email: "Application Integration", states: "Application Integration",
  iam: "Security, Identity & Compliance", sts: "Security, Identity & Compliance", "cognito-idp": "Security, Identity & Compliance",
  kms: "Security, Identity & Compliance", secretsmanager: "Security, Identity & Compliance", acm: "Security, Identity & Compliance",
  wafv2: "Security, Identity & Compliance",
  cloudformation: "Management & Governance", monitoring: "Management & Governance", logs: "Management & Governance",
  ssm: "Management & Governance", config: "Management & Governance", appconfig: "Management & Governance",
  appconfigdata: "Management & Governance", cloudtrail: "Management & Governance", servicediscovery: "Management & Governance",
  athena: "Analytics", glue: "Analytics", firehose: "Analytics", kafka: "Analytics", es: "Analytics", emr: "Analytics",
  "bedrock-runtime": "Machine Learning", textract: "Machine Learning", transcribe: "Machine Learning",
  ce: "Cost Management", cur: "Cost Management", "bcm-data-exports": "Cost Management", pricing: "Cost Management", tagging: "Cost Management",
  codedeploy: "Developer Tools", codebuild: "Developer Tools",
  backup: "Migration & Transfer", transfer: "Migration & Transfer",
  batch: "Analytics",
};

export const SERVICE_LABELS: Record<string, string> = {
  "s3": "S3",
  "s3vectors": "S3 Vector Search",
  "sqs": "SQS",
  "sns": "SNS",
  "lambda": "Lambda",
  "dynamodb": "DynamoDB",
  "iam": "IAM",
  "sts": "STS",
  "kms": "KMS",
  "secretsmanager": "Secrets Manager",
  "cloudformation": "CloudFormation",
  "events": "EventBridge",
  "ssm": "Systems Manager",
  "kinesis": "Kinesis",
  "logs": "CloudWatch Logs",
  "monitoring": "CloudWatch Metrics",
  "ec2": "EC2",
  "ecs": "ECS",
  "ecr": "ECR",
  "rds": "RDS",
  "elasticache": "ElastiCache",
  "memorydb": "MemoryDB",
  "cognito-idp": "Cognito",
  "acm": "ACM",
  "route53": "Route 53",
  "cloudfront": "CloudFront",
  "apigateway": "API Gateway",
  "apigatewayv2": "API Gateway V2",
  "athena": "Athena",
  "glue": "Glue",
  "firehose": "Kinesis Firehose",
  "states": "Step Functions",
  "kafka": "MSK",
  "es": "OpenSearch",
  "servicediscovery": "Cloud Map",
  "scheduler": "EventBridge Scheduler",
  "pipes": "EventBridge Pipes",
  "email": "SES",
  "elasticloadbalancing": "ELB",
  "neptune": "Neptune",
  "codebuild": "CodeBuild",
  "codedeploy": "CodeDeploy",
  "eks": "EKS",
  "backup": "Backup",
  "transfer": "Transfer Family",
  "cloudtrail": "CloudTrail",
  "appconfig": "AppConfig",
  "appconfigdata": "AppConfig Data",
  "bedrock-runtime": "Bedrock Runtime",
  "textract": "Textract",
  "transcribe": "Transcribe",
  "pricing": "Pricing",
  "ce": "Cost Explorer",
  "cur": "Cost & Usage Report",
  "bcm-data-exports": "BCM Data Exports",
  "tagging": "Resource Groups Tagging",
  "config": "Config",
  "autoscaling": "Auto Scaling",
  "appsync": "AppSync",
  "wafv2": "WAF v2",
  "ec2messages": "EC2 Messages",
  "batch": "AWS Batch",
  "docdb": "DocumentDB",
  "emr": "Amazon EMR",
  "rdsdata": "RDS Data API",
};

export function getServiceLabel(externalKey: string): string {
  return SERVICE_LABELS[externalKey] ?? externalKey;
}
